site_name: COWFS
site_description: Copy-on-Write Filesystem built with FUSE
site_url: https://atikulmunna.github.io/COW-Filesystem/
repo_url: https://github.com/atikulmunna/COW-Filesystem
repo_name: atikulmunna/COW-Filesystem

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Architecture: architecture.md
  - CLI Reference: cli.md
  - Release Guide: release.md
